//src/app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";

import { QueryClient, dehydrate } from '@tanstack/react-query';
import ReactQueryProvider from '@/lib/ReactQueryProvider';
import { getData } from "@/services/data";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {


    const queryClient = new QueryClient();
  
  await queryClient.prefetchQuery({ 
    queryKey: ['mydata'],
    queryFn: getData
   });

  const dehydratedState = dehydrate(queryClient);

  return (
   <html lang="en">
      <body>
        <ReactQueryProvider dehydratedState={dehydratedState}>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
